### ISSUE TITLE
python 3.11 support

### ISSUE THREAD

**Issue by Nosterx** [natasha/natasha#120]
На данный момент пакет зависит от pymorphy2 который, [судя по всему](https://github.com/pymorphy2/pymorphy2/issues/159), умер и уже не будет обновляться. Кажется можно легко пофиксить это переехав на живой форк https://github.com/no-plagiarism/pymorphy3/pull/7

**Comment by kuk** [comment]
Есть надежда оживить pymorphy2, сделал патч https://github.com/pymorphy2/pymorphy2/pull/161

**Comment by 1a11** [comment]
К сожалению, всё ещё мертва. Оч прошу пофиксить или хотя бы поправить импорт у морфа поддержкой pymorphy3

**Comment by mlipkovich** [comment]
Присоединяюсь к запросу. Спасибо!

**Comment by kuk** [comment]
pip install natasha==1.6.0 Должен работать на Python 3.11. Пожалуйста, проверьте
