### ISSUE TITLE
ImportError: cannot import name 'NamesExtractor'

### ISSUE THREAD

**Issue by bekerov** [natasha/natasha#23]
Пакет установился корректно, при копипасте документации, выходит ошибка.
ImportError: cannot import name 'NamesExtractor'

В пакете указаны следующие импорты:
![image](https://user-images.githubusercontent.com/2405629/30326631-d149d706-97d1-11e7-90d6-fe05206ab71e.png)

это в документации указано некорректно или чтото при установке не доставилось?

**Comment by dveselov** [comment]
Привет.
Судя по импортам, вы используете версию, которая сейчас есть на PyPI (которую можно установить так: `pip install natasha`) и у неё отдельная документация: http://natasha.readthedocs.io/ru/0.7.0/?badge=0.7.0
А то, что написано в README и сам `NamesExtractor` доступен в последней версии парсера, которую можно установить так:
```
pip install git+https://github.com/natasha/natasha.git#egg=natasha
```

**Comment by bekerov** [comment]
спасибо, я также ставил через python setup.py install
и выдается ошибка 
```
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/Projects/Prototypes/tmp.py", line 1, in <module>
    from natasha import NamesExtractor, DatesExtractor, MoneyExtractor
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\__init__.py", line 2, in <module>
    from .extractors import (
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\extractors.py", line 8, in <module>
    from .utils import Record
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\utils.py", line 3, in <module>
    from yargy.utils import Record
ImportError: cannot import name 'Record'
```

**Comment by alexanderkuk** [comment]
Установите ещё версию yargy с гитхаба. По аналогии
```
pip install git+https://github.com/natasha/yargy.git#egg=yargy
```

**Comment by bekerov** [comment]
в коде он требует файл first.txt
но в репозитории и в egg его нет.
```
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/Projects/Prototypes/tmp.py", line 1, in <module>
    from natasha import NamesExtractor, DatesExtractor, MoneyExtractor
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\__init__.py", line 2, in <module>
    from .extractors import (
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\extractors.py", line 12, in <module>
    from .grammars.name import NAME
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\grammars\name.py", line 25, in <module>
    FIRST_DICT = set(load_lines('first.txt'))
  File "C:\Users\admin\Anaconda2\envs\python35\lib\site-packages\natasha\data\__init__.py", line 21, in load_lines
    with open(path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\admin\\Anaconda2\\envs\\python35\\lib\\site-packages\\natasha\\data\\first.txt'
```

**Comment by alexanderkuk** [comment]
В репозитории он есть https://github.com/natasha/natasha/blob/master/natasha/data/first.txt

**Comment by bekerov** [comment]
если ставить так:
`pip install https://github.com/natasha/natasha/archive/master.zip`
то в архиве тоже есть, а вот в папку, куда ставится библиотека, уже нет
![image](https://user-images.githubusercontent.com/2405629/30422411-8743a678-9948-11e7-8c40-3d59281ac243.png)

**Comment by alexanderkuk** [comment]
Да, странно, попробуйте так
```
git clone https://github.com/natasha/yargy.git
cd yargy
pip install -e .

git clone https://github.com/natasha/natasha.git
cd natasha
pip install -e .
```

**Comment by bekerov** [comment]
Несмотря на то, что я добавил эти словари, и все работает, либа не находит русские имена и фамилии

**Comment by bekerov** [comment]
с датами все ок

**Comment by alexanderkuk** [comment]
По моим оценкам, качество извлечения имён от 75% до 90% в зависимости от текста. Вы можете завести отдельный тикет с ошибками

**Comment by bekerov** [comment]
я пробую тестовый пример

**Comment by alexanderkuk** [comment]
Вы можете завести отдельный тикет, туда написать проблемный текст и приложить ваш код
