### ISSUE TITLE
Не работает тестовый пример для выделения имен

### ISSUE THREAD

**Issue by bekerov** [natasha/natasha#27]
Использую [тестовый пример](http://natasha.readthedocs.io/ru/latest/) на windows 7, python3.5
Установил либы так

```
git clone https://github.com/natasha/yargy.git
cd yargy
pip install -e .

git clone https://github.com/natasha/natasha.git
cd natasha
pip install -e .
```

```
from natasha import NamesExtractor

text = '''
Простите, еще несколько цитат из приговора. «…Отрицал существование
Иисуса и пророка Мухаммеда», «наделял Иисуса Христа качествами
ожившего мертвеца — зомби» [и] «качествами покемонов —
представителей бестиария японской мифологии, тем самым совершил
преступление, предусмотренное статьей 148 УК РФ
'''
extractor = NamesExtractor()
matches = extractor(text)

for match in matches:
    print(match.span, match.fact)
```

Скрипт отрабатывает не выводя никаких имен.

**Comment by alexanderkuk** [comment]
Честно говоря, не знаю как вам помочь. Может быть вы что-то не так установили. Может быть какие-то проблемы связанные с windows, мы кажется там не тестировали код

**Comment by bekerov** [comment]
Попробовал на python2 установить, и отработало.
похоже на проблему с кодировками в 3 версии питона.

**Comment by bekerov** [comment]
так проблема то не решена)

**Comment by alexanderkuk** [comment]
Мы выяснили, что на windows библиотека работает. На Python 3 библиотека тоже работает, это мы проверяем. Остаётся версия, что вы что-то не так установили

**Comment by bekerov** [comment]
локализовал проблему, там при открытии файла проблема. надо указать кодировку.
сделать пр?

**Comment by alexanderkuk** [comment]
Да не, вроде не надо. Может быть вы вручную подложили файл и он у вас не в utf8?

**Comment by bekerov** [comment]
нет, специально переставил полностью. тут не подкладывал

**Comment by alexanderkuk** [comment]
ок, что вы поменяли в коде?

**Comment by bekerov** [comment]
Вобщем проблема решается для 3 питона открытием файла так
```
 with open(path, encoding="utf-8") as file:
```
Но для второго так не работает. 
я предпочитаю через codecs работать для обратной совместимости

**Comment by alexanderkuk** [comment]
А, понятно, на windows дефолтная кодировка cp1251. Да, сделайте, пожалуйста, pull request

**Comment by bekerov** [comment]
https://github.com/natasha/natasha/pull/28
