### ISSUE TITLE
Падают тесты

### ISSUE THREAD

**Issue by stcoder** [natasha/natasha#39]
Попытался запустить тесты, упали с ошибкой

> platform darwin -- Python 3.6.3, pytest-3.2.1, py-1.5.2, pluggy-0.4.0 -- /Users/stcoder/workenv/other/parser-test/venv/bin/python
cachedir: .cache
rootdir: /Users/stcoder/workenv/other/parser-test/natasha, inifile:
plugins: pep8-1.0.6
collected 24 items / 7 errors 

Вот одна из семи ошибок (остальные жалуются на тоже самое):
> ../venv/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
natasha/__init__.py:2: in <module>
    from .extractors import (
natasha/extractors.py:16: in <module>
    from .grammars.address import ADDRESS, ComplexGorodPipeline
natasha/grammars/address.py:136: in <module>
    Region.type.const('федеральный округ')
E   AttributeError: 'FactAttribute' object has no attribute 'const'

**Comment by dveselov** [comment]
Привет, нужно поставить `yagry` из master-ветки: https://github.com/natasha/yargy:
```
pip uninstall yargy
pip install https://github.com/natasha/yargy/archive/master.zip
```

**Comment by stcoder** [comment]
Спасибо, тикет можно закрыть
