### ISSUE TITLE
Длина строки

### ISSUE THREAD

**Issue by stcoder** [natasha/natasha#41]
Как то можно задать в правилах чтоб длина строки была от **x** до **y**?

Например правило ниже поймет такое выражение: `123-321-432-234`
`SEP = eq('-')`
`INT = gram('INT')`
`rule(INT, rule(SEP, INT, SEP.optional()).optional()).repeatable()`

Вот мне нужно определить длину данного выражение чтоб оно было длинее например 5 символов но меньше 7

**Comment by kuk** [comment]
Такое можно сделать только на пособработке. 

```
matches = parser.findall(...)
for match in matches:
    start, stop = match.span
    if 5 <= stop - start <= 7:
       ...

```
