### ISSUE TITLE
Как можно использовать список городов

### ISSUE THREAD

**Issue by tonal** [natasha/natasha#44]
Есть задача классифицировать строки состоящие из одного слова.
В каждой строке название города, но может встречаться мусор.
Можно ли как-то использовать списки городов из пакета для решения этой задачи?

**Comment by alexanderkuk** [comment]
Вы можете взять словари из https://github.com/natasha/natasha/blob/master/natasha/grammars/address.py#L460 . Использовать Наташу мне кажется тут излишне

**Comment by tonal** [comment]
Задача несколько изменилась - в строках встречались префиксы, типа "г."
Так что оказалось нужно просто создать свой классификатор по аналогии:
```python
class CityExtractor(Extractor):
  def __init__(self):
    super().__init__(GOROD, [ComplexGorodPipeline()])
```

**Comment by tonal** [comment]
Соответственно возникает вопрос #45 (Как можно добавить города в список городов)
