### ISSUE TITLE
Как можно добавить города в список городов

### ISSUE THREAD

**Issue by tonal** [natasha/natasha#45]
В даных встречаются города, которых нет в списках.
Например Алдан, г. Лиски (Воронежская область), Минск, или г.Ниний Новгород.

Как можно расширить список городов понимаемый пакетом?

**Comment by alexanderkuk** [comment]
Есть переменные SIMPLE и COMPLEX в https://github.com/natasha/natasha/blob/master/natasha/grammars/address.py#L468 .

**Comment by tonal** [comment]
На прямую к ним не обратишься - они переопределяются ниже https://github.com/natasha/natasha/blob/master/natasha/grammars/address.py#L696
Стало быть нужно обращаться через другие правила. Что несколько неудобно:
```
RESPUBLIKA_NAME.rule.rules[0].productions[0].children[0].value.add('удмуртия')
GOROD_NAME.rule.productions[0].children[0].predicates[0].value.add('алдан')
GOROD_NAME.rule.productions[0].children[0].predicates[0].value.add('магнитагорск')
GOROD_NAME.rule.productions[0].children[0].predicates[0].value.add('минск')
GOROD_NAME.rule.productions[0].children[0].predicates[-1].value.add('нск')
```
Да и состав правил может меняться (например в версии 0.8.0, последний из pip-а, `COMPLEX = gram('ComplexGorod')`)

Может как-то стандартизировать эти манипуляции?

**Comment by Desklop** [comment]
Здравствуйте, @kuk 
Пробовал добавить значения в переменную `SIMPLE` (город минск и остальные областные центры Беларуси), но эффекта это не дало.
То, что советовал @tonal - если честно, не понимаю как сделать. Не нахожу подобных строк в `grammars/address.py`.
Можете пожалуйста подсказать, как правильно это делать, добавлять новые значения (города)?
Стоит самая последняя версия, доступная через `pip` - 0.10.0.

**Comment by kuk** [comment]
Правильным способом добавить город в список городов будет скопировать правила из Наташи к себе в проект и модифицировать список, использовать Yargy напрямую.
