### ISSUE TITLE
Create a convertor from and to Yandex Tomita-Parser format

### ISSUE THREAD

**Issue by KOLANICH** [natasha/natasha#52]

**Comment by alexanderkuk** [comment]
Функциональность Ярги и Томиты пересекается, но не полностью. Приведите, пожалуйста, конкретные примеры, для которых такой конвертор будет полезен

**Comment by KOLANICH** [comment]
Cannot find concrete examples, but on github a one can find some grammars for tomita-parser, i'd be nice if a one can use them without rewriting to yarg manually
