### ISSUE TITLE
Translate into haxe

### ISSUE THREAD

**Issue by KOLANICH** [natasha/natasha#54]
Haxe is a lang translated into a variety of languages like JS, python, c++, c#, and java. Since only python dependency is yqrgy, which only large dependency is pymorphy, I guess it may be possible to isolate it into abstraction layer and for other languages use mystem or other available library instead.

**Comment by dveselov** [comment]
Исходный код парсера и грамматик открыт, всё в ваших руках.
Поддерживать и дорабатывать не python версию мы пока не планируем, увы.
