### ISSUE TITLE
Нормализация именованных сущностей

### ISSUE THREAD

**Issue by dveselov** [natasha/natasha#6]
После реализации https://github.com/bureaucratic-labs/yargy/issues/3, для некоторых типов сущностей (например, персона) производить нормализацию становится очень легко.
Поэтому можно добавить такую возможность.

**Comment by dveselov** [comment]
На всякий случай: Popov A. M., Adaskina Yu. V., Andreyeva D. A., Charabet Ja., Moskvina A. D., Protopopova E. V., Yushina T. A. [Named Entity Normalization for Fact Extraction Task](http://www.dialog-21.ru/media/3456/popovametal.pdf)  (доклад на конференции "Диалог'16")

**Comment by dveselov** [comment]
Начиная с версии `0.4.0` снимается омонимия для имен собственных и некоторых типов организаций (например, связанные с образованием - `в стенах [Санкт-Петербургского государственного университета] ...`)

**Comment by dveselov** [comment]
(иногда снимается частично)

**Comment by dveselov** [comment]
Пример нормализации упоминаний (в формате `оригинальный текст | нормализованный текст`)
```bash
Основатель MySQL Майкл Видениус | основатель MySQL Майкл Видениус 
Лидер оппозиции Нино Бурджанадзе | лидер оппозиции Нино Бурджанадзе 
президента Грузии Михаила Саакашвили | президент Грузии Михаил Саакашвили 
глава внешнеполитического ведомства России Сергей Лавров | глава внешнеполитического ведомства России Сергей Лавров 
президента России Дмитрия Медведева | президент России Дмитрий Медведев 
Премьер-министр Владимир Путин | премьер-министр Владимир Путин 
президент Дмитрий Медведев | президент Дмитрий Медведев 
писателя Александра Дмитриева | писатель Александр Дмитриев 
министром обороны России Анатолием Сердюковым | министр обороны России Анатолий сердюков 
руководитель балета Большого театра Алексей Ратманский | руководитель балета Большого театра Алексей ратманский 
Министр финансов РФ Алексей Кудрин | министр финансов РФ Алексей Кудрин 
премьер-министр РФ Владимир Путин | премьер-министр РФ Владимир Путин 
царь Иоанн Грозный | царь Иоанн Грозный 
царь Иоанн Грозный | царь Иоанн Грозный 
президента РФ Дмитрия Медведева | президент РФ Дмитрий Медведев 
губернатора Бориса Громова | губернатор Борис Громов 
король Майкл Джексон | король Майкл Джексон 
заместителем министра иностранных дел Грузии Александром Налбандовым | заместитель министра иностранных дел Грузии Александр Налбандов 
```

**Comment by dveselov** [comment]
Стоит подумать над нормализацией имен - `митя -> дима -> дмитрий`
Сейчас в голову приходит только отдельный газеттир, описывающий сокращенные формы и заменяющий их на полные формы (потому, что в корпусе между ними нет связей - http://opencorpora.org/dict.php?act=edit&id=83944, в отличии от http://opencorpora.org/dict.php?act=edit&id=62141)

**Comment by TiberiumPY** [comment]
@dveselov а можно пример, как использовать нормализацию в своём коде?

**Comment by dveselov** [comment]
Привет.
Нужно поставить [yargy](https://github.com/bureaucratic-labs/yargy) и [natasha](https://github.com/bureaucratic-labs/natasha) из master бранча, дальше всё просто
```python
from natasha import Combinator
from natasha.grammars import Person
from yargy.normalization import get_normalized_text

combinator = Combinator([Person])

grammar, tokens = next(
    combinator.resolve_matches(
        combinator.extract(
            'с василисой смирновой произошло невероятное ...',
        )
    )
)

normalized_text = get_normalized_text(tokens)
assert grammar == Person.FirstnameAndLastname
assert normalized_text == 'василиса смирнова'
```

**Comment by TiberiumPY** [comment]
@dveselov спасибо!

**Comment by dveselov** [comment]
https://github.com/bureaucratic-labs/yargy/issues/19

**Comment by dveselov** [comment]
Давно с этим разобрались, вроде бы.
