### ISSUE TITLE
Natasha не распознает имена с маленькой буквы

### ISSUE THREAD

**Issue by Hedgehogues** [natasha/natasha#61]
text = '''
сергей
'''
extractor = NamesExtractor()
matches = extractor(text)
for match in matches:
    print(match.span, match.fact)

**Comment by alexanderkuk** [comment]
Если нужно работать с именами с маленькой буквы вне контекста можно попробовать `SimpleNamesExtractor`

```
from natasha import SimpleNamesExtractor
text = '''
сергей
сергей ионов
'''
extractor = SimpleNamesExtractor()
matches = extractor(text)
for match in matches:
    print(match.span, match.fact)
```

Если нужно работать с именами с маленькой буквы внутри предложений (кстати когда это реально нужно?), то тут сложно.

**Comment by Hedgehogues** [comment]
Есть текста, которые написаны целиком заглавными буквами, без знаков препинания.

**Comment by murfel** [comment]
Капитализируйте текст, будет тот же эффект.

**Comment by alexanderkuk** [comment]
`Есть текста, которые написаны целиком заглавными буквами, без знаков препинания`
Откуда эти тексты берутся? speech recognition?

Для таких текстов нужно натренировать другой crf классификатор.

**Comment by Hedgehogues** [comment]
Смысл тогда юзать Наташу? Если всегда можно натренировать другой классификатор?

**Comment by alexanderkuk** [comment]
В Наташе извлечение имён идёт в два этапа: разметка crf-теггером, применение правил с помощью yargy-парсера. Для текстов с один регистром нужно модифицировать первый этап, подготовить другую модель для crf-теггера, второй этап с правила останется без изменений. 

Именно на втором этапе подстрока с именем разбивается на часть имя, фамилия, отчество, проверяется согласование и части приводятся к нормальной форме
