### ISSUE TITLE
Как добавить больше имён и правило FIRST_LAST не изменяя файлов библиотеки?

### ISSUE THREAD

**Issue by AlexKrimi** [natasha/natasha#62]
Привет. Недавно начал пользоваться вашей библиотекой. Я хочу добавить побольше имён и фамилий в словарь
1) как добавить имена, не изменяя файл /data/dicts.first.txt ?
функция load_dict в __init__ загружает все имена на старте, а если я хочу добавить имён для Наташи?
2) есть ли метод добавить правило FIRST_LAST = rule(FIRST, LAST) не редактируя файла /grammars/name.py ?

**Comment by kuk** [comment]
> 1. как добавить имена, не изменяя файл /data/dicts.first.txt ?
> функция load_dict в init загружает все имена на старте, а если я хочу добавить имён для Наташи?

> 2. есть ли метод добавить правило FIRST_LAST = rule(FIRST, LAST) не редактируя файла /grammars/name.py ?

Если стандартное решение не подходит по качеству, нужно скопировать правила и словари к себе в проект и модифицировать.
