### ISSUE TITLE
Нормализацтя дат в числа с ведущим нулем.

### ISSUE THREAD

**Issue by Armyanin** [natasha/natasha#65]
Как можно заставить парсер выдавать цифры даты с ведущими нулями?
Наример 5 февраля 2018 вернет {year=2018,month=2,day=5}, надо {year=2018,month=02,day=05}
Спасибо

**Comment by alexanderkuk** [comment]
Возможно вам поможет просто форматирование даты 

```
'{year:04d}-{month:02d}-{day:02d}'.format(year=2018, month=12, day=5)
'2018-12-05'
```

**Comment by Armyanin** [comment]
Где этот код должен работать?
