### ISSUE TITLE
Вопрос по правильному написанию правила со свободным текстом в середине 

### ISSUE THREAD

**Issue by asyncee** [natasha/natasha#67]
Добрый день! Спасибо за замечательную библиотеку!

Такой вопрос — имеется строка "один произвольный текст два три". Задача — выделить два факта из этой строки:

- один
- два три

и интерпретировать их как цельный факт "один два три"

Проблема в том, что в середине может находиться произвольный текст. Можно ли средствами natasha задать правило, допускающее любые токены внутри правила?

На данный момент решить задачу можно с помощью получения всех matches для входных данных и анализировать уже их, но я хотел бы этого избежать и задать правило вида rule(ONE, ANY_TOKENS, TWO_THREE).

Спасибо!

**Comment by alexanderkuk** [comment]
Это вопрос по https://github.com/natasha/yargy. К сожалению, нормального способа такое сделать в yargy нет, хотя вопрос возникает не первый раз, есть варианты:
1. Если мы знаем с какого токена начинается конец фразы, можно написать `rule('один', not_(eq('два')).repeatable(), 'три')`. Но это сломается на "один произвольный два текст два три"
2. Если мы знаем сколько максимум токенов может быть между фразами, можно написать `rule('один', true().repeatable(max=5), 'два', 'три')`. Но это плохо по производительности, и неочевидная константа с потолка
3. Если ни первое ни второе, можно два раза запустить парсер, найти сначала "один", потом "два три", склеить из них новую строчку и запустить парсер в третий раз

**Comment by asyncee** [comment]
Спасибо за ответ!
