### ISSUE TITLE
crf-теггер

### ISSUE THREAD

**Issue by teemiik** [natasha/natasha#70]
Здравствуйте. Есть какая-то инструкция по обучение crf-теггера или хотя бы справка, интересует вопрос дообучения теггера имен.

**Comment by alexanderkuk** [comment]
Пока такой инструкции нет

**Comment by kuk** [comment]
Библиотека перешла на другой тип моделей, cfr-теггер не используется. Скрипт обучения https://github.com/natasha/slovnet/blob/master/scripts/05_ner/main.ipynb
