### ISSUE TITLE
Python 2.7 не поддерживается?

### ISSUE THREAD

**Issue by kuzmaka** [natasha/natasha#71]
Безуспешно попытался запустить тестовый пример на Python 2.7.15, хотя в readme указано, что Python 2.7+ поддерживается. 

* Исходная ошибка на той же строке, что и в #31, хотя причина в тикете описана неверно.
* Если вместо нормализации дефисов вернуть ту же строку, а дефисы из текста убрать, то тестовый пример выполняется без ошибок, но ничего не выводит.

На Python 3.7.3 запустил без проблем.

**Comment by kuk** [comment]
Python 2 больше не поддерживается
