### ISSUE TITLE
MoneyExtractor - некорректное распознавание больших чисел

### ISSUE THREAD

**Issue by vboyadzhi** [natasha/natasha#72]
Пример:
```
from natasha import MoneyExtractor
text = 'какой-то текст 1.844.036.360,12 руб. какой-то текст'
extractor = MoneyExtractor()
matches = extractor(text)
print(matches[0].fact.normalized.amount)
```

`844036360.12`

хотя должно быть
`1844036360.12`

**Comment by kuk** [comment]
Правильным решением здесь будет скопировать правила из Наташи к себе в проект и модифицировать. Надо поменять https://github.com/natasha/natasha/blob/master/natasha/grammars/money.py#L235
