### ISSUE TITLE
Перегрев CPU

### ISSUE THREAD

**Issue by Expert73** [natasha/natasha#73]
Столкнулся с достаточно специфической проблемой - перегрев CPU. i9700k.
В 1 поток модуль работает ожидаемо корректно. Но если запараллелить через модуль multiprocessing мгновенный скачок температуры до 90 градусов.
Греет вот эта инструкция matches = extractor(elem).

От себя отмечу, что очень давно использую модуль pymorphy2 в своих проектах, параллельные вычисления. И при прочих равных условиях нагрев не больше 70 градусов.
Какие инструкции процессора использует ваш модуль? есть предположение, что очень активно задействуются инструкции семейства avx.

**Comment by kuk** [comment]
Эм, natasha написана на чистом python, не использует какие-то низкоуровневые инструкции
