### ISSUE TITLE
Фамилии в которых присутствует буква "Ё" неверно распознаются

### ISSUE THREAD

**Issue by galinovivan** [natasha/natasha#77]
Есть такой код
`from natasha.extractors import NamesExtractor
e = NamesExtractor()
matches = e('Соловьёва Татьяна')
for m in matches:
  print(m.fact)`
В итоге парсер распознает только имя, если заменить 'ё' на е, фамилия распознается

**Comment by kuk** [comment]
Библиотека значительно обновилась, результат на вашем примере корректный

```
from natasha import NamesExtractor, MorphVocab

vocab = MorphVocab()
extractor = NamesExtractor(vocab)
extractor.find('Соловьёва Татьяна')

Match(
    start=0,
    stop=17,
    fact=Name(
        first='Татьяна',
        last='Соловьёва'
    )
)

```
