### ISSUE TITLE
Добавить правила для извлечения ИНН, ОГРН, LEI, ОКУД

### ISSUE THREAD

**Issue by lechatb** [natasha/natasha#82]
Правила ИНН: https://ru.wikipedia.org/wiki/%D0%98%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0
Правила ОГРН: 
https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80

Правила LEI https://www.gleif.org/ru/about-lei/introducing-the-legal-entity-identifier-lei

Правила ОКУД: https://classifikators.ru/okud

Практически всегда "ИНН" и "ОГРН"  пишется перед самим кодом.

**Comment by kuk** [comment]
Думаю это задача для отдельной библиотеки. Наташа про обработку естественного русского языка. Извлечение кодов — это регулярные выражения + код для проверки контрольных сумм, тут нет работы с естественным русским языком.
