### ISSUE TITLE
Непонятные ошибки

### ISSUE THREAD

**Issue by Expert73** [natasha/natasha#83]
Переустановил python 3.8.2 и соответственно переустановил модуль natasha.
Ранее рабочий код стал сыпаться ошибками.

Например вот этот участок кода:
from natasha import NamesExtractor
from natasha.markup import (
    show_markup_notebook as show_markup,
    format_json
)

extractor = NamesExtractor()

получаю  ошибку
Traceback (most recent call last):
  File "1.py", line 7, in <module>
    extractor = NamesExtractor()
TypeError: __init__() missing 1 required positional argument: 'morph'

Как и что подправить?

**Comment by Expert73** [comment]
Или вот такая ошибка
    from yargy.utils import Record
ModuleNotFoundError: No module named 'yargy.utils'

**Comment by kuk** [comment]
С версии 1.0 интерфейс библиотеки поменялся, см. README https://github.com/natasha/natasha. Чтобы использовать прежний интерфейс установить соответствующую версию `pip install natasha<1 yargy<0.13`

**Comment by Expert73** [comment]
В примере ошибки быть не может?
from natasha import (
    Segmenter,
    MorphVocab,
    
    NewsEmbedding,
    NewsMorphTagger,
    NewsSyntaxParser,
    NewsNERTagger,
    
    PER,
    NamesExtractor,
    DatesExtractor,
    MoneyExtractor,
    AddrExtractor,

    Doc
)

segmenter = Segmenter()
morph_vocab = MorphVocab()

emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)
syntax_parser = NewsSyntaxParser(emb)
ner_tagger = NewsNERTagger(emb)

names_extractor = NamesExtractor(morph_vocab)
dates_extractor = DatesExtractor(morph_vocab)
money_extractor = MoneyExtractor(morph_vocab)
addr_extractor = AddrExtractor(morph_vocab)

text = 'Очень длинный текст примера '
doc = Doc(text)

Мне нужно извлечь только имена. Насколько вижу doc до момента извлечения имен не переопределяется

for span in doc.spans:
    if span.type == PER:
        span.extract_fact(names_extractor)
    
{_.normal: _.fact for _ in doc.spans if _.fact}

получаю ошибку
    for span in doc.spans:
TypeError: 'NoneType' object is not iterable

**Comment by Expert73** [comment]
все понял. вопрос снимаю

**Comment by kactetus** [comment]
> получаю ошибку
> for span in doc.spans:
> TypeError: 'NoneType' object is not iterable

Точная такая же ошибка, как решили?

**Comment by dimameh** [comment]
> получаю ошибку
> for span in doc.spans:
> TypeError: 'NoneType' object is not iterable
И у меня. Как решается то?
