### ISSUE TITLE
Exception  TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by hodzanassredin** [natasha/natasha#84]
text = 'и -‐'
doc = Doc(text)
doc.segment(segmenter)
doc.tag_morph(morph_tagger)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by kuk** [comment]
Thank you for bug report. Fixed in https://github.com/natasha/slovnet/commit/392f17178d1f2ecc580d893f55700ea696ce41f7 . Please `pip install slovnet>=0.4.0`
