### ISSUE TITLE
Ошибка display(...

### ISSUE THREAD

**Issue by evgeniy0712** [natasha/natasha#89]
Здравствуйте! Подскажите (юристу) не получается запустить выдаёт ошибку после выполнения команды >>> display(...
Пишет имя не определено. Подскажите в чем проблема?

**Comment by kuk** [comment]
Замените display на print.

display работает в Jupyter Notebook.

**Comment by evgeniy0712** [comment]
Спасибо огромное!



Отправлено из мобильной Почты Mail.ru


среда, 14 октября 2020 г., 18:38 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by evgeniy0712** [comment]
Принял!💪



Отправлено из мобильной Почты Mail.ru


среда, 14 октября 2020 г., 18:38 +0300 от notifications@github.com  <notifications@github.com>:
