### ISSUE TITLE
Добавить грамматики для названий улиц

### ISSUE THREAD

**Issue by dveselov** [natasha/natasha#9]
Т.е. для названий площадей, проспектов, станций метро? (точно не уверен, кажется проще создать отдельный газеттир)
Касаемо улиц - есть правила, которые закрывают ~80% названий:
* прил + сущ (Большая Садовая улица / улица Зеленая)
* сущ + слова в родительном падеже (улица Лени Голикова / набережная реки Фонтанки)
* сущ + число + слова в родительном падеже (улица 50-летия Октября / площадь 1905 года)

Дополнительно можно добавить грамматики для поиска полноценных адресов (типа Санкт-Петербург, 3-я улица Строителей, дом 25, квартира 12)

**Comment by alexanderkuk** [comment]
В [address_lines.txt.zip](https://github.com/bureaucratic-labs/natasha/files/746281/address_lines.txt.zip) 369 427 строчек вида
```
Адрес: г. Барнаул, пр-т. Ленина, д. 71
Офис и шоу-рум в Красноярске работает с 14.00 до 17.00 по адресу г.Красноряск ул.Парижской Коммуны,14 оф.14.
Юридический адрес: 129344, г. Москва, ул. Искры, дом 31, корпус 1, пом. II комната 7А.
г. Пятигорск, ул. Февральская, д. 54
Дмитровское шоссе, д.157, стр.9
603070, г. Нижний Новгород, ул. Акимова 22 «А»
Адрес: | г. Санкт-Петербург, ул. Шамшева, д. 8 (ДК им.В.А.Шелгунова)
Факт. и юр. адрес: 426052, г. Ижевск, ул. Лесозаводская 23/110
Адрес: Россия г. Санкт-Петербург ул. Чехова 14 оф23
129085, Москва, ул.Годовикова д.9  (Бизнес-центр "Калибр").
Почтовый адрес: Россия, 693010 г. Южно-Сахалинск, Комсомольская, 154, оф. 600
ул. Менжинского, 4г ст. А
ул. Менжинского, 4г ст. Б
344010, РФ, г. Ростов-на-Дону, ул. Красноармейская д.208, офис 302.
Юридический адрес 308000, Белгородская обл., г.Белгород, ул.Н.Островского, д.5
Юридический, физический и фактический адрес: 350072, г. Краснодар, ул. Московская, 5.
Российская Федерация, Тверская область, Кимрский район, пгт.  Белый Городок, улица Заводская дом 11
Свердловская обл., г. Екатеринбург, Барвинка 21
196084 Россия,Санкт-Петербург ул. Киевская д.6 корп.1 лит. Б
Адрес: г. Москва, ул. Бутырская, д. 86Б, ст.м. Дмитровская
Адрес: г. Раменское, ул. Дергаевская, д. 32
Телефон/факс: (49331) 2-36-72 ~ e-mail: privpravda@mail.ru ~ г.Кинешма, ул.Правды, д.4, третий этаж.
Адрес: г. Москва, ул.Дубнинская, 79 влад.А
г. Краснодар, ул. Северная, 314
Адрес: : Краснодарский край, 353440, г. Анапа, ул. Кирова, 72/3
(C) 2015-2016 Геодренаж г. Екатеринбург, ул. Фронтовых Бригад, 15, офис 301/1
601501 г. Гусь-Хрустальный,  ул. Интернациональная,д.11
Адрес: 119048, Москва, 3-я Фрунзенская ул., дом 19
6 | ООО "Тольяттисинтез" | 445007, ул.Новозаводская, 8, Тольятти, Самарская обл. | (8482) 36-90-00 | www.tltk.ru
...
```

Возможно, такие данные помогут отладить грамматики для поиска адресов.

Как были получены данные. Грубо говоря был сделан греп интернета по регулярке вида `д\.|комн\.|м\.|ост\.|пом\.|стр\.|лит\.|ст\.|а/я|п/я|oф\.|с\.|обл\.|ул\.|пр-т|проспект\b|г\.|адрес\b|бульвар\b|область\b|улица\b|шоссе\b|переулок\b|дом\b|комната\b|помещение\b|корпус\b`. Обрабатывались страницы с контактной информацией организаций типа http://lemon-ku.ru/contacts, http://gk-meta.ru/contacts/

Мне было бы интересно заняться этим таском. Есть практические задачи, где нужно выделять адреса. Текущие решения, которые мы используем меня не очень устраивают. И, вообще, проект Наташа, мне кажется полезным и хочется подробнее в нём разобраться, попробовать применить для своих задач.

**Comment by dveselov** [comment]
Супер, спасибо!
Если решите этим заняться, то в документации есть небольшой пример грамматики для разбора названий улиц (http://natasha.readthedocs.io/ru/latest/grammars/#id4) - можно начать с неё

**Comment by dveselov** [comment]
Написал базовые правила для названий улиц в 882f7094fea864342d5e906bd251353a27b33b69
В [вложении](https://yadi.sk/i/bksOHfHn3ChYBf) результат разбора приведенного выше датасета в формате:
```
--------
TEXT: Республика, Башкортостан, г.Уфа, ш. Уфимское, дом № 39
MATCH:
ORIGINAL TEXT: ш. Уфимское
GRAMMAR: Address.AdjShort
NORMALIZED: ш . Уфимское
--------
TEXT: Адрес: ул. Малиновского, д. 23Д
MATCH:
ORIGINAL TEXT: ул. Малиновского
GRAMMAR: Address.GentShortReversed
NORMALIZED: ул . Малиновского
--------
TEXT: Адрес: Колокольников переулок, д.9, стр.5, Москва, 107045
NO MATCHES
--------
TEXT: г. Сочи, ул. Изобильная, д. 27
MATCH:
ORIGINAL TEXT: ул. Изобильная
GRAMMAR: Address.AdjShort
NORMALIZED: ул . Изобильная
--------
TEXT: Юридический адрес:     123423 г. Москва, ул. Народного Ополчения, д. 11, 143
MATCH:
ORIGINAL TEXT: ул. Народного Ополчения
GRAMMAR: Address.AdjNounShort
NORMALIZED: ул . Народное Ополчение
--------
TEXT: ул. Гельсингфорсская, д. 2, лит. А,
MATCH:
ORIGINAL TEXT: ул. Гельсингфорсская
GRAMMAR: Address.AdjShort
NORMALIZED: ул . Гельсингфорсская
--------
TEXT: Адрес:  ул. Республики, 40/1
MATCH:
ORIGINAL TEXT: ул. Республики
GRAMMAR: Address.GentShortReversed
NORMALIZED: ул . Республики
```
Всего было веделено `315180` названий, т.е. около 85% (если считать, что в каждой строке указан
 адрес), про точность пока ничего сказать не могу.

**Comment by dveselov** [comment]
Нужно будет дописать грамматики для полных адресов (название улицы, номер дома, корпуса, квартиры и т.д.)

**Comment by dveselov** [comment]
Актуально для нового парсера.

**Comment by dveselov** [comment]
Вернули в https://github.com/natasha/natasha/pull/22

**Comment by TatyanaDenko** [comment]
Здравствуйте. Может вообще не по адресу, но есть такая задача..... В программе 1С вручную забиты адреса зданий. Нужно их распознать и транспонировать в адреса справочника ФИАС. Какая то программа может это сделать?
