### ISSUE TITLE
Обнаружение дат и времени, номеров автомобилей и т.д.

### ISSUE THREAD

**Issue by glorsh66** [natasha/natasha#91]
Не смог найти способа как вытаскивать даты, время и номера автомобилей из текста.
Примеры в интернете для старого  API

from natasha.markup import show_markup, show_json

extractors = [
    NamesExtractor(),
    AddressExtractor(),
    DatesExtractor(),
    MoneyExtractor()
]

for extractor in extractors:
    matches = extractor(text)
    spans.extend(_.span for _ in matches)
    facts.extend(_.fact.as_json for _ in matches)
show_markup(text, spans)
show_json(facts)

**Comment by kuk** [comment]
В проекте Natasha готовых правил для времени и номеров автомобилей нет. Вы можете разработать их с помощь Yargy парсера, документация https://github.com/natasha/yargy/#documentation
