### ISSUE TITLE
python3.9 показывает ошибку при попытке поиска именных сущностей (NER) (Все делалось по  README)

### ISSUE THREAD

**Issue by rokatyy** [natasha/natasha#97]
![image](https://user-images.githubusercontent.com/35141662/105359608-b15ba880-5c08-11eb-961a-0de392f4b33f.png)

**Comment by kuk** [comment]
Попробуйте перед запуском ner, сделать сегментацию `doc.segment(segmenter)` в README

**Comment by rokatyy** [comment]
@kuk Заработало! Спасибо :)
